/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking.system;

/**
 *
 * @author nguy
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashboardPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        accountBalance = new javax.swing.JLabel();
        orderCheque = new javax.swing.JLabel();
        billPayment = new javax.swing.JLabel();
        instantPaymentTransfer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");

        DashboardPanel.setBackground(new java.awt.Color(255, 255, 255));
        DashboardPanel.setForeground(new java.awt.Color(255, 255, 255));
        DashboardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardPanelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DASHBOARD");

        accountBalance.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        accountBalance.setForeground(new java.awt.Color(0, 0, 0));
        accountBalance.setText("Account Balance");
        accountBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountBalanceMouseClicked(evt);
            }
        });

        orderCheque.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        orderCheque.setForeground(new java.awt.Color(0, 0, 0));
        orderCheque.setText("Order Cheque Book");
        orderCheque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderChequeMouseClicked(evt);
            }
        });

        billPayment.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        billPayment.setForeground(new java.awt.Color(0, 0, 0));
        billPayment.setText("Bill Payment");
        billPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billPaymentMouseClicked(evt);
            }
        });

        instantPaymentTransfer.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        instantPaymentTransfer.setForeground(new java.awt.Color(0, 0, 0));
        instantPaymentTransfer.setText("Instant Payment Transfer");
        instantPaymentTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instantPaymentTransferMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jLabel2.setText("Logout");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DashboardPanelLayout = new javax.swing.GroupLayout(DashboardPanel);
        DashboardPanel.setLayout(DashboardPanelLayout);
        DashboardPanelLayout.setHorizontalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardPanelLayout.createSequentialGroup()
                .addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DashboardPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountBalance)
                            .addComponent(billPayment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instantPaymentTransfer)
                            .addComponent(orderCheque)))
                    .addGroup(DashboardPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(221, 221, 221))
                    .addGroup(DashboardPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(48, 48, 48))
        );
        DashboardPanelLayout.setVerticalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instantPaymentTransfer)
                    .addComponent(accountBalance))
                .addGap(30, 30, 30)
                .addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billPayment)
                    .addComponent(orderCheque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardPanelMouseClicked

    private void billPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billPaymentMouseClicked
        // TODO add your handling code here:
        billpayment obj = new billpayment();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_billPaymentMouseClicked

    private void instantPaymentTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instantPaymentTransferMouseClicked
        // TODO add your handling code here:
        instantpayment obj = new instantpayment();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_instantPaymentTransferMouseClicked

    private void orderChequeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderChequeMouseClicked
        // TODO add your handling code here:
        ordercheque obj = new ordercheque();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_orderChequeMouseClicked

    private void accountBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountBalanceMouseClicked
        // TODO add your handling code here:
        accountbalance obj = new accountbalance();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_accountBalanceMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        LoginPage obj = new LoginPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JLabel accountBalance;
    private javax.swing.JLabel billPayment;
    private javax.swing.JLabel instantPaymentTransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel orderCheque;
    // End of variables declaration//GEN-END:variables
}
